client_config_backend: settings
client_config:
  client_id: 887552104258-qrmaq3bnm0jlmtsu38aokiso0elebboq.apps.googleusercontent.com
  client_secret: NhbquT9RtQh30SuJ_tMbr9xX

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive